// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcl5U-2x2bYdVY6zazyYSWW64RAXGLr3o',
    appId: '1:445824990075:web:2edbcaff7c57d013e09bde',
    messagingSenderId: '445824990075',
    projectId: 'testing-51e22',
    authDomain: 'testing-51e22.firebaseapp.com',
    storageBucket: 'testing-51e22.appspot.com',
    measurementId: 'G-BJJ6PTR28X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRL_1eeN9LLi3wx4SH3tRen1JVjnJ2Iag',
    appId: '1:445824990075:android:fe9582b79240bd5ee09bde',
    messagingSenderId: '445824990075',
    projectId: 'testing-51e22',
    storageBucket: 'testing-51e22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjBBL1e8VaCMAdbr34IY-9LNsfi-8vSAs',
    appId: '1:445824990075:ios:a7f87f61aec740e7e09bde',
    messagingSenderId: '445824990075',
    projectId: 'testing-51e22',
    storageBucket: 'testing-51e22.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjBBL1e8VaCMAdbr34IY-9LNsfi-8vSAs',
    appId: '1:445824990075:ios:a7f87f61aec740e7e09bde',
    messagingSenderId: '445824990075',
    projectId: 'testing-51e22',
    storageBucket: 'testing-51e22.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcl5U-2x2bYdVY6zazyYSWW64RAXGLr3o',
    appId: '1:445824990075:web:2b0fc18bfcbcdf21e09bde',
    messagingSenderId: '445824990075',
    projectId: 'testing-51e22',
    authDomain: 'testing-51e22.firebaseapp.com',
    storageBucket: 'testing-51e22.appspot.com',
    measurementId: 'G-GPFG178E7Y',
  );
}
